[package]
name = "mcp-hello-world"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.101"
flexi_logger = "0.31.8"
log = "0.4.29"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
tokio = { version = "1.49.0", features = ["full"] }
